### ISSUE TITLE
As a registered user I want to provide my acceptable methods of communication with quick replies

### ISSUE THREAD

**Issue by lex** [kehitysto/coaching-chatbot#33]
# Acceptance criteria

- MB should ask for communication methods when the user asks to start searching for a pair
- MB must ask for the user to provide an acceptable method of communication from a list of quick replies
- Available options are: Skype, Phone, Cafe
- MB must provide as options only the one's that have not yet been chosen
- If no more options are remaining MB should move forward automatically
- MB must repeat asking this until the user chooses to proceed
- Preferred methods of communication must be saved to DB

**Comment by amv** [comment]
needs also a way to edit mistakes. otherwise looks good.
