### ISSUE TITLE
As a registered user I want to provide my user name (or phone number) for my selected acceptable methods of communication

### ISSUE THREAD

**Issue by lex** [kehitysto/coaching-chatbot#34]
## Acceptance criteria

- MB must ask for username if user chooses Skype as an acceptable communication method
- MB must ask for phone number if user chooses phone or cafe as an acceptable method of communication
- Username and/or phone number must be saved to DB

**Comment by amv** [comment]
i thought there is no longer a preferred communication method, but a list of acceptable ones - and each of them would need a contact method.
